// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqmrshvhtdhmcxjxvdqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbXJzaHZodGRobWN4anh2ZHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzYwNzUsImV4cCI6MjA3NDY1MjA3NX0.Kq9j9vnkf5e4xhJvzgfmFbmx7JaMy18uVqKBCT6p1U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});